name:                pm
version:             0.1.0.0
github:              "LeoQiao18/pm"
license:             BSD3
author:              "Leo Qiao"
maintainer:          "qiaofeitong@hotmail.com"
copyright:           "Leo Qiao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LeoQiao18/pm#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - matrix

executables:
  pm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pm
    when:
    - condition: false
      other-modules: Paths_pm

tests:
  chess-test:
    main:                Spec.hs
    source-dirs:         test/chess
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pm
    - hspec
